# Generated by Django 6.0.2 on 2026-02-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
