# Generated by Django 6.0.2 on 2026-02-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('education', models.CharField(max_length=200)),
                ('year_passed', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('full', 'Full Amount'), ('emi', 'Installment EMI')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
